DROP DATABASE IF EXISTS github;
CREATE DATABASE github;

\connect github

DROP TABLE IF EXISTS ACTOR;
CREATE TABLE ACTOR(
	id INT	NOT NULL,
	login VARCHAR (200)	NOT NULL,
	url VARCHAR (200) NOT NULL,
	avatar_url VARCHAR(200),
	PRIMARY KEY(id),
):

DROP TABLE IF EXISTS EVENT;
CREATE TABLE EVENT(
	id INT	NOT NULL,
	type VARCHAR (200)	NOT NULL,
	repository_name VARCHAR (200),
	actor_id INT	NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY (actor_id) REFERENCES ACTOR(id)
);

DROP TABLE IF EXISTS PUSH_EVENT;
CREATE TABLE PUSH_EVENT(
	commit_count INT NOT NULL,
	branch_name VARCHAR(200) NOT NULL
) INHERITS(EVENT);

DROP TABLE IF EXISTS CREATE_EVENT;
CREATE TABLE CREATE_EVENT(
	description VARCHAR (200) NOT NULL,
	ref_types VARCHAR(200) NOT NULL,
	ref VARCHAR (200) NOT NULL
) INHERITS(EVENT);
